language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: true
script:
- echo "Skipping tests because we haven't setup a server to use"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: D4hBpGXtUFC5UD6qWD3W0GCLVE7LyJlscT/wrHQ2wmlvWR01oK1nGoALW1wo/SFvAFApjucBQtHiTzJos3qVMqc4DHgI2DJOIjkmxIONjJTRvqI7DNt0ZUyiTHxCW4vbKdna47fSSV1wWnl8dgR/XdXHx3DqpRTJyfUKQNGD9UfT2RkpxUwrGqrg/at29wyaAaM7vM1iO0pHDxn0U87CDlqPfD2I32BpSbK0/aORJl7PXVamd1UCHXy3jRm3T2vLhKdUE3CXohm4xDsr4xHY/94UzEq/i9CjDZx97UJ3PUTC/chEYOdVCO1E/268T3+MS5Hy9PFkoAOFYLaLh0GxCASpmJBWcNokCWJb9HH/hCAnLB0RNU8LqEKFwtso7xfuBDe4Vk59mFbpiGHFEtKZZRdaQwE+/Eaupo4reQKs6CTQtE1Hen9Iabyk1IxS9ym7/cOtLysTzX6ZTUJAXM2c+wGCoU09EH/144qWtR0NPOrpFsVnjvb+3xeLx04kLsAHhjXckPt7eHR2GXIz21izq0u7IidIlU115dWhE0fChmlc4KvUKfQ8oeMC/xJGCL6HapEMubDxjZ+Vap3PMAyL57Opi/69A+qbCAgZxvQ2mjHAJqGwx32NuHtD12KefKP+knoNfv3q3HEHBIowM0DbK7fsUrg9SBhgvyLq/c/jI38=
  on:
    tags: true
    repo: mcneilco/acasclient
    python: 3.8
