name: Launch ACAS and run python tests

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
jobs:
  acas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout acasclient
        uses: actions/checkout@v3
        with:
          path: acasclient
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install acasclient and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./acasclient
      - name: Set ACAS_TAG to latest release
        run: |
          echo "ACAS_TAG=$(curl -s https://api.github.com/repos/mcneilco/acas/releases/latest | jq -r '.tag_name')" >> $GITHUB_ENV
      - name: Checkout ACAS
        uses: actions/checkout@v3
        with:
          repository: mcneilco/acas
          path: acas
          ref: ${{ env.ACAS_TAG }}
      - name: Run docker-compose up - assumes racas-oss:${{ env.ACAS_TAG }} and acas-roo-server-oss:${{ env.ACAS_TAG }}-indigo exist and are up to date
        id: dockerComposeUp
        working-directory: acas
        run: |
          docker-compose -f "docker-compose.yml" up -d
      - name: Wait for startup then create docker bob
        run: bash docker_bob_setup.sh
        working-directory: acas
      - name: Create bob credentials for acasclient
        run: |
          mkdir ~/.acas
          echo "[default]" >> ~/.acas/credentials
          echo "username=bob" >> ~/.acas/credentials
          echo "password=secret" >> ~/.acas/credentials
          echo "url=http://localhost:3000" >> ~/.acas/credentials
      - name: Run tests
        run: python -m unittest discover -s ./acasclient -p "test_*.py" -v